export const GET_USERS = "GET_USERS"
export const GET_USERS_REQUESTED = 'GET_USERS_REQUESTED'
export const ADD_USER = "ADD_USER"
export const ADD_USER_REQUESTED = 'ADD_USER_REQUESTED'
export const EDIT_USER = "EDIT_USER"
export const EDIT_USER_REQUESTED = 'EDIT_USER_REQUESTED'
export const DELETE_USER_REQUESTED = 'DELETE_USER_REQUESTED'